### ISSUE TITLE
farmer section: header closes/shifts about 10 sec after opening

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/www_grid#12]
please fix that header get shifted up:

https://docs.google.com/document/d/12vtDJlE1620zBw8elabJr9TDtLdQVuujD8b1xd6yTN4/edit#heading=h.1x44kdb3t4e9

click to see yourself: https://www2.grid.tf/threefold-farming.html

**Comment by ehab-hassan** [comment]
also because of iframe when it loads it show if it first then back(that the reason of shifted)
