### ISSUE TITLE
help center section: change on support 

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/www_grid#16]
please change from email only to new support tool and integrate in i frame:
https://support.grid.tf/

i frame instead of contact us:
<img width="676" alt="grafik" src="https://user-images.githubusercontent.com/18591016/58082168-bad07a00-7bb6-11e9-8199-e9dd15a04002.png">

Text above i frame:
Have a persistent problem, found a bug, or a feature request?

Our new ticketing system is still in beta. Please help us to iron out the last glitches. Thank you

Text below i frame:
Our new ticketing system will go in production 1st of June 2019.

**Comment by ehab-hassan** [comment]
this link
https://www2.grid.tf/ has protected cant be Iframe it overwrites the page

**Comment by VonSub** [comment]
it's no longer in, closed.
