### ISSUE TITLE
grdi.tf mobile: grid usage get capacity.threefoldtoken.com displayed right 

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/www_grid#3]
page https://www2.grid.tf/grid-usage.html
capacity.threefoldtoken.com needs to be displayed fully
![image](https://user-images.githubusercontent.com/18591016/57979566-e9681c80-7a1f-11e9-9dbc-07e28f68e9ed.png)

**Comment by ehab-hassan** [comment]
done
