### ISSUE TITLE
grid.tf mobile: grid usage reservation Step 5 reservation examples not displayed correct

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/www_grid#4]
page https://www2.grid.tf/grid-usage.html
Step 5: please fix 3 examples so they are displayed correct on mobile

![image](https://user-images.githubusercontent.com/18591016/57979577-16b4ca80-7a20-11e9-9e1f-4768a8988e4a.png)

**Comment by ehab-hassan** [comment]
because of this image screenshots, where I can find the source of this  image so I can edit in high resolution

**Comment by VonSub** [comment]
grid usage is out. closed.
